version: '3.0'

services:
  webapp:
    build:
      context: ../webapp/rust
    init: true
    working_dir: /home/isucon/webapp/rust
    container_name: webapp
    volumes:
      - ../webapp/sql:/home/isucon/webapp/sql
      - ../webapp/img:/home/isucon/webapp/img
      - ../webapp/public:/home/isucon/webapp/public
    environment:
      ISUCON13_MYSQL_DIALCONFIG_ADDRESS: mysql
      ISUCON13_POWERDNS_HOST: powerdns
      ISUCON13_POWERDNS_SUBDOMAIN_ADDRESS: 127.0.0.1
    ports:
      - "127.0.0.1:8080:8080"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4g
    depends_on:
      mysql:
        condition: service_healthy
