{
 "title": "Default Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": " 累積実行時間/API",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "app_request_duration_seconds_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MySQL Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(max_over_time(mysql_global_status_threads_connected[$__interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(mysql_global_status_max_used_connections)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "MySQL QPS",
   "type": "timeseries",
   "description": "Query Per Second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_queries[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "mysql_global_variables_innodb_buffer_pool_size",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Slow Query",
   "type": "timeseries",
   "description": "Not Working?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "rate(mysql_global_status_slow_queries[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}